# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d87162b993653021456133bbd27f2afb0155a4038a14fb8acf61900fd7a9d762c66dfcbe9a3eab522da072521056eec8d3587be9fa632f448635d7543d7fe04

test:
  secret_key_base: 6a19637225ec4c95a9d13631f4c0e0960b2ca6b59af949c6dfdda8fff6c1f7ed03e2f402f7ca395dea5b1a849b537f34b63fa7b6707e3c0716dc380ff5cb4125

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
